server:
  port: 8081

spring:
  application:
    name: stock-quote-manager
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  jmx:
    enabled: false
  datasource:
    #url: jdbc:mysql://stock-mysql:3306/bootdb?allowPublicKeyRetrieval=true&sslMode=DISABLED&useTimezone=true&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/bootdb?allowPublicKeyRetrieval=true&sslMode=DISABLED&useTimezone=true&serverTimezone=UTC
    username: root
    password: root